# Generated by Django 5.1.5 on 2025-02-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_last_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='last_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='reminder_days',
        ),
    ]
